#!/bin/bash
# mdiff.sh -- created 2009-01-27, <+NAME+>
# @Last Change: 24-Dez-2004.
# @Revision:    0.0

PREFIX_TO_APPEND="\/home\/michal\/prg\/java\/workspace\/SOFA2_TRUNK\/"
PREFIX_TO_CLEAR=".*workspace_klesnil_sofa_branch\/sofa\/"

if [ $# -ne 1 ]; then
        echo "Usage $0 <filename-to-diff>"
        exit 1
fi

FFILENAME=$(basename $1)
FFILE_DIR=$(cd $(dirname $1); pwd)

FFILE_TO_DIFF=$FFILE_DIR/$FFILENAME

SFILE_TO_DIFF=`echo "$FFILE_TO_DIFF" | sed -e "s/$PREFIX_TO_CLEAR/$PREFIX_TO_APPEND/"`

if [ ! -f "$SFILE_TO_DIFF" ]; then
        echo "File $SFILE_TO_DIFF does not exist... Exiting"
        exit 1;
fi

vimdiff $FFILE_TO_DIFF $SFILE_TO_DIFF
# vi: 
